# Generated by Django 3.2.15 on 2022-09-06 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED')], default='PENDING', max_length=100)),
                ('mtdone', models.BooleanField(default=False)),
                ('update_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'db_table': 'job',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('name_iso_639_1', models.CharField(max_length=2)),
                ('name_iso_639_2', models.CharField(max_length=3)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'db_table': 'language',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LanguagePair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('src_lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='src_lang', to='translate.language')),
                ('tgt_lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tgt_lang', to='translate.language')),
            ],
            options={
                'verbose_name': 'Language Pair',
                'verbose_name_plural': 'Language Pairs',
                'db_table': 'language_pair',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MyTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('sent_id', models.IntegerField(null=True)),
                ('text', models.TextField()),
                ('translate_text', models.TextField(null=True)),
                ('characters', models.IntegerField(default=0)),
                ('update_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(null=True)),
                ('engine', models.TextField()),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='translate.job')),
                ('lang_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translate.languagepair')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Translation',
                'verbose_name_plural': 'Translations',
                'db_table': 'translation',
                'ordering': ['id'],
            },
        ),
    ]
