# Generated by Django 3.2.15 on 2022-09-07 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0002_deepltranslation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mytranslation',
            name='job',
        ),
        migrations.RemoveField(
            model_name='mytranslation',
            name='lang_pair',
        ),
        migrations.RemoveField(
            model_name='mytranslation',
            name='user',
        ),
        migrations.DeleteModel(
            name='DeepLTranslation',
        ),
        migrations.DeleteModel(
            name='MyTranslation',
        ),
    ]
