# Generated by Django 3.2.15 on 2022-09-07 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('translate', '0003_auto_20220907_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('sent_id', models.IntegerField(null=True)),
                ('text', models.TextField()),
                ('translate_text', models.TextField(null=True)),
                ('characters', models.IntegerField(default=0)),
                ('engine', models.TextField()),
                ('trained_model', models.BooleanField(default=True)),
                ('external_model', models.TextField(null=True)),
                ('confidence', models.FloatField(null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(null=True)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='translate.job')),
                ('lang_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translate.languagepair')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Translation',
                'verbose_name_plural': 'Translations',
                'db_table': 'translation',
                'ordering': ['id'],
            },
        ),
    ]
