# Generated by Django 3.2.15 on 2022-09-13 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0006_auto_20220908_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='name_iso_639_3166',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('QUEUED', 'QUEUED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('CANCELLED', 'CANCELLED'), ('ERROR', 'ERROR'), ('COMPLETED', 'COMPLETED')], default='PENDING', max_length=100),
        ),
    ]
