# Generated by Django 3.2.15 on 2022-09-13 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0007_auto_20220913_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='languagepair',
            name='src_lang',
        ),
        migrations.RemoveField(
            model_name='languagepair',
            name='tgt_lang',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='lang_pair',
        ),
        migrations.AddField(
            model_name='translation',
            name='src_lang',
            field=models.CharField(default='en', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='translation',
            name='tgt_lang',
            field=models.CharField(default='fr', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='LanguagePair',
        ),
    ]
