# Generated by Django 3.2.15 on 2022-08-26 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mtuser',
            table=None,
        ),
    ]
